name: autoGrader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_valgrind
      run: sudo apt install -y valgrind
    - name: cmake
      run: cmake -S .
    - name: make
      run: make
    - name: ctest
      run: ctest --output-on-failure
    - name: make memcheck
      if: success() || failure()
      run: make valgrind
